### ISSUE TITLE
quick start node version

### ISSUE THREAD

**Issue by bettybao1209** [nspcc-dev/neofs-dev-env#101]
Hi, I'd like to know which version of neo is the dev-env based on? Since the wallet is not compatible for the two types of nodes.

**Comment by alexvanin** [comment]
dev-env based on N3 RC3 version of Neo blockchain. It uses neo-go [v0.95.3](https://github.com/nspcc-dev/neo-go/releases/tag/v0.95.3) which is RC3-compatible.

**Comment by bettybao1209** [comment]
> dev-env based on N3 RC3 version of Neo blockchain. It uses neo-go [v0.95.3](https://github.com/nspcc-dev/neo-go/releases/tag/v0.95.3) which is RC3-compatible.

Nice, thanks for the reply.
