### ISSUE TITLE
shebang in makefile

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-dev-env#145]
https://github.com/nspcc-dev/neofs-dev-env/blob/5462a5dee82e58e4804b8d0ad2be63f7bbba144e/Makefile#L1

What's this for?

**Comment by realloc** [comment]
Ancient sysadmin tradition.

**Comment by 532910** [comment]
Should be removed, I believe.

**Comment by realloc** [comment]
No, let's leave it as is. Allows to run default make target as a script, that's nice.

**Comment by 532910** [comment]
1. This makefile requires a target as it prints out a help message by default.
2. It's not executable.
