### ISSUE TITLE
Do not use underscores in hostnames

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-dev-env#164]
Devenv doesn't work properly on my machine. Seems like the problem is with underscores in hostnames (same problem occurs with curl which is used in `bin/*.sh` scripts:

```
мар 03 15:29:29 wpc systemd-resolved[255752]: /etc/hosts:9: hostname "main_chain.neofs.devenv" is not valid, ignoring.
мар 03 15:29:29 wpc systemd-resolved[255752]: /etc/hosts:18: hostname "morph_chain.neofs.devenv" is not valid, ignoring.
мар 03 15:29:29 wpc systemd-resolved[255752]: /etc/hosts:21: hostname "*.s3.neofs.devenv" is not valid, ignoring.
```

I am not sure what update caused the issue, because it worked in the last year. We should use `morph-chain` instead. Another problem is with `*.s3.neofs.devenv`, do we need this record? @KirillovDenis @alexvanin

**Comment by KirillovDenis** [comment]
As I understand it was done to resolve `https://bucketname.s3.neofs.devenv` but aws cli, for example, use different endpoint format `https://s3.neofs.devenv/bucketname`. And during local development I suppose we do without `*.s3.neofs.devenv` hostname

**Comment by 532910** [comment]
underscore is invalid character in domain and host name
