### ISSUE TITLE
why some files are hidden?

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-dev-env#169]
`.dockerignore`, `.gitignore`, `.git`, `.editorconfig` are hidden, but they are not a part of this project, just a helpers for git and others.

And the question is: why `.env`, `.services` and `.basic_services` start with dot?

**Comment by alexvanin** [comment]
¯\\_(ツ)_/¯ 
I don't think there is a particular reason for that. Moreover other dotenv files such as `service/ir/.ir.env` and `service/storage/.storage.env` are also hidden. 
Are there any issues with it, though?

**Comment by 532910** [comment]
`service/ir/.ir.env` and `service/storage/.storage.env` also should be unhidden

**Comment by alexvanin** [comment]
I don't mind having those files unhidden. Should not affect developer's workflow, however it might require some changes in integration tests. @aprasolova can you check that?

**Comment by aprasolova** [comment]
In integration tests, we only use [.int_test.env](https://github.com/nspcc-dev/neofs-dev-env/blob/master/.int_test.env). I'm okay with unhide of the files.
@EliChin

**Comment by roman-khimov** [comment]
I think this property will make it easier to reintegrate dev-env into the main node repository. WONTFIX here.
