### ISSUE TITLE
Error when make up

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-dev-env#17]
**Reproduce**
Git clone repo and run `make up`.
Error:
![image](https://user-images.githubusercontent.com/22324403/100595980-99695600-3336-11eb-9a39-5c8cd836a5c1.png)

**Env**
Make: `GNU Make 3.81`
OS: `macOS Big Sur 11.0.1`
Shell: `zsh 5.8 (x86_64-apple-darwin20.0)`

**Comment by realloc** [comment]
I'm not sure if other featured, like docker networking, will work on macOS. We don't test dev-env on Mac platform.
Is it possible for you to update `make` and see if the issue resolves?

**Comment by ZhangTao1596** [comment]
`GNU Make 4.3` works well. My fault.
