### ISSUE TITLE
Bump `MaxGasInvoke` in morph chain

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-dev-env#207]
After #197 it is very convenient to use neofs-adm for contract deployment. However it produces some heavy transactions due to NNS contract invocation. Deploying contract with `yadayada.neofs` domain requires 30+ GAS. 

What do you think about bumping config value for morph chain, let's say, up to 100 GAS. Or maybe use values from our test stands.

/cc @fyrchik @KirillovDenis @carpawell @realloc @anatoly-bogatyrev @aprasolova

**Comment by realloc** [comment]
The only problematic use-case for this is initial custom contracts deployment. The GAS price issue is handled by `neofs-adm` for this case. If we increase the limit we may miss the issues relevant for the real environments where the GAS limit is not that high.

We plan to use dev-env for integration tests, so I'd propose to keep the limit same as we have in public networks.

**Comment by carpawell** [comment]
@alexvanin, does https://github.com/nspcc-dev/neofs-node/pull/1683 solve the problem? (do not be confuse by its title, the solution changed during discussion)

**Comment by alexvanin** [comment]
> @alexvanin, does [nspcc-dev/neofs-node#1683](https://github.com/nspcc-dev/neofs-node/pull/1683) solve the problem? (do not be confused by its title, the solution changed during discussion)

It does (v0.31.0-39-gb54f34d7). I'll close it next week if no other comments will appear.

**Comment by alexvanin** [comment]
> The only problematic use-case for this is initial custom contracts deployment

So it does interfere with our plan to use `neofs-adm` for contract deployment without pre-configured chains.
