### ISSUE TITLE
REST Gateway + NeoFS Panel services

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-dev-env#210]
We have publishes [NeoFS REST Gateway](https://github.com/nspcc-dev/neofs-rest-gw/) and almost ready to publish web app to manage NeoFS assets. REST Gateway instance is already a part of [neofs-aio](https://github.com/nspcc-dev/neofs-aio/pull/29). So we can add both gateway and app to the dev-env.

Possible issues:
- local wallet app is required,
- web app and wallet connect private net connection may require nginx to handle CORS.

[aero](https://aero.coz.io/) wallet has some flaws (/cc @KirillovDenis)
- it can't be used with nep-6 wallets from dev-env, we need separate short JSON wallet,

**Comment by KirillovDenis** [comment]
Currently we get the following error when try to sign token:
```
2.aed965b6.chunk.js:1 Mixed Content: The page at 'https://aero.coz.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://main-chain.neofs.devenv:30333/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by alexvanin** [comment]
Maybe we can add only REST GW, it can list container info. Also neofs-cli can generate bearer token (can it?)

**Comment by alexvanin** [comment]
Done in #217 
Panel is going to be available from panel repo.
