### ISSUE TITLE
Notary service can no longer be disabled in the Sidechain

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-dev-env#245]
After #208 Dev Env cannot launch Sidechain without Notary service because NeoFS Adm requires it. Following [docs](https://github.com/nspcc-dev/neofs-dev-env/blob/master/docs/notary.md#disable-notary-service-in-side-chain) leads to:
```
Error: initialization error: notary contract must be enabled
```

According to this requirement, we should declare that the Sidechain can't be denotarized, and corresponding docs must be actualized.

Any other thoughts? @roman-khimov @fyrchik @alexvanin @carpawell

**Comment by roman-khimov** [comment]
Related to nspcc-dev/neofs-node#2192, but non-notary will be removed, so not a big deal.

**Comment by roman-khimov** [comment]
After #249 this mode can't really be.
