### ISSUE TITLE
initialization error: can't create N3 client

### ISSUE THREAD

**Issue by antonlavrenov** [nspcc-dev/neofs-dev-env#248]
make prepare-test-env завершается ошибкой. Подскажите, что сделать, чтобы поправить?

Creating network "basenet_internet" with driver "bridge"
Creating bastion ...
Creating bastion ... done
up/bootstrap for service: chain
Creating network "chain_chain_int" with the default driver
Creating main_chain ...
Creating main_chain ... done
up/bootstrap for service: morph_chain
Creating network "morph_chain_chain_int" with the default driver
Creating morph_chain ...
Creating morph_chain ... done
Error: initialization error: can't create N3 client: failed to get network magic: Post "http://morph-chain.neofs.devenv:30333": dial tcp: lookup morph-chain.neofs.devenv on 127.0.0.53:53: no such host
: Failed to initialize Alphabet wallets
make[1]: *** [Makefile:115: up/bootstrap] Error 1
make[1]: Leaving directory '/home/ubuntu/neofs-dev-env'
Test environment setup failed. Please check the error messages above.
make: *** [Makefile:227: prepare-test-env] Error 1

**Comment by roman-khimov** [comment]
`make hosts >> /etc/hosts`?

**Comment by antonlavrenov** [comment]
"make hosts >> /etc/hosts"  did not solve the problem

The command "make up/basic" helped before "make prepare-test-env".
¯ \ _ (ツ) _ / ¯

it's work now.

**Comment by antonlavrenov** [comment]
How to increase the balance to create container?

neofs-cli --rpc-endpoint s01.neofs.devenv:8080 -w wallets/wallet.key container create --basic-acl public-read-write --await --policy "REP 1 IN X CBF 1 SELECT 1 FROM * AS X"
put container rpc error: status: code = 1024 message = neofs error: chain/client: contract execution finished with state FAULT; exception: at instruction 2145 (THROW): unhandled exception: "insufficient balance to create container"

**Comment by roman-khimov** [comment]
https://github.com/nspcc-dev/neofs-dev-env/blob/master/docs/morph.md#side-chain-wallets
https://github.com/nspcc-dev/neofs-dev-env/blob/master/docs/chain.md#neofs-gas-deposit

**Comment by antonlavrenov** [comment]
Thank you
