### ISSUE TITLE
Update rest-gw config for version 0.6.0 

### ISSUE THREAD

**Issue by tatiana-nspcc** [nspcc-dev/neofs-dev-env#301]
## Is your feature request related to a problem? Please describe.

Now I cannot change only the version in the  file https://github.com/nspcc-dev/neofs-dev-env/blob/b7f7f1114850d360eca866a0822a3eab566ea699/.env , because there were several config changes between versions 0.5.0. and 0.6.0. 

## Describe the solution you'd like

Add changes in the next files:
1. https://github.com/nspcc-dev/neofs-dev-env/blob/b7f7f1114850d360eca866a0822a3eab566ea699/services/rest_gate/cfg/config.yml
2. https://github.com/nspcc-dev/neofs-dev-env/blob/b7f7f1114850d360eca866a0822a3eab566ea699/services/rest_gate/docker-compose.yml
3. https://github.com/nspcc-dev/neofs-dev-env/blob/b7f7f1114850d360eca866a0822a3eab566ea699/.env
4. somewhere else?

Accordingly to change log: https://github.com/nspcc-dev/neofs-rest-gw/blob/4a394ecd2289617cf8fcd5db286e6bee7f6bed40/CHANGELOG.md

**Comment by roman-khimov** [comment]
Fixed in #308.
