### ISSUE TITLE
Specify contract script hashes in global .env

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-dev-env#47]
Contract script hashes are reused by inner ring nodes and storage nodes. Configuration record keys are different for these applications, however values are the same. Can we define all script hashes in a global scope and then reuse these variables in application specific `.<servce>.env` files?

E.g:
```
.env:
NETMAP_CONTRACT=bb8398295bd3a232a68068dbfab32b898eb29600

services/ir/.ir.env:
NEOFS_IR_CONTRACTS_NETMAP=$NETMAP_CONTRACT

servicest/storage/.storage.env:
NEOFS_NETMAP_SCRIPTHASH=$NETMAP_CONTRACT
```

/cc @realloc @cthulhu-rider @pkorotkov @anatoly-bogatyrev

**Comment by realloc** [comment]
Sure, good idea.

**Comment by carpawell** [comment]
Me and @cthulhu-rider could not find "clean" solution for reusing one's `.env` file variable in another, therefore, I proposed my solution in #57 and created #58 issue, if a better solution appears in docker-compose somewhen in the future.

**Comment by alexvanin** [comment]
Solution at #57 is not quite suitable (see @realloc comment there), so we should find out better way to do that (or not to do it at all). I duplicate @carpawell  insights from #58 in this task.

> Find a better solution for reusing scripthashes in .env filed.
>
> Now scripthashes from root .env file are used for initializing internal service-specific environmental variables via variable substitution in docker-compose file once per every service(7 IR + 4 SN). It was realized in such a way because no better solution was found/implemented in docker-compose's reading environmental process.
>
> E.g.: Could be solved with using envsubst util.

**Comment by anatoly-bogatyrev** [comment]
NNS will be zero contract to contract address auto-detection.
This task will be modified to:
- add NNS contract deployment to prepared morph chain in the dev-env
- update dev-env .env configs
It can be done after NeoFS NNS contract support.
