### ISSUE TITLE
Use expect to automate password input in neo-go commands

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-dev-env#70]
There are plenty Makefile targets which invoke neo-go to deposit assets or change global configuration of neofs. However all these invocations require manual password input. It is a bit ugly and we can use `expect` utility in our scripts to avoid it.

**Comment by aprasolova** [comment]
Let's avoid using expect. Instead, you might derive wallet from WIF with python script. [Here's](https://github.com/nspcc-dev/neofs-keywords/blob/master/wallet_keywords.py#L43) the example function.

**Comment by alexvanin** [comment]
>  Instead, you might derive wallet from WIF with python script.

I am not sure how it will help to run neo-go command without password input.

**Comment by alexvanin** [comment]
Done in https://github.com/nspcc-dev/neofs-dev-env/pull/83
