### ISSUE TITLE
Implement service state sync

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-dev-env#72]
There should be a way to synchronize services' starting states and wait until a service is in a working state before starting another once. For example, both mainnet and sidechain must be up and start creating blocks before InnerRing is started.

Though all services MUST properly handle such situation at application level, this enhancement could improve dev-env usability.

**Comment by cthulhu-rider** [comment]
Storage node and IR (after https://github.com/nspcc-dev/neofs-node/issues/414) can return health status. The easiest way to get the status is to exec NeoFS CLI `control healthcheck` command. 

Unfortunately there is no `neofs-cli` program in images.

**Comment by alexvanin** [comment]
This issue blocks #84
