### ISSUE TITLE
Number of CNs and IR nodes should be configurable

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-dev-env#73]
In different development and testing scenarios we require different number of IR/CN/other nodes. It should be configurable and different setup scripts should be used depending on those settings.

**Comment by roman-khimov** [comment]
It's not that difficult to generate a small chain dump (and I don't think you have a lot to put into it), neo-bench does that for example.

**Comment by realloc** [comment]
In the most simple case this can be implemented as additional separate services, like `chain-single` and `ir-single`. Depending on the most popular configurations, they may be disabled or enabled by default. Chain dump urls could be pre-set in those services.

**Comment by alexvanin** [comment]
Let's start with polishing and publishing our chain generation tools first.

**Comment by aprasolova** [comment]
As I understood from the discussion, the task is about creating exact neofs-dev-env configurations with predefined number of nodes and corresponding blockchain dumps. If it is so, I only need to know, how many nodes must be in these configurations.
@realloc @alexvanin ?

**Comment by alexvanin** [comment]
> As I understood from the discussion, the task is about creating exact neofs-dev-env configurations with predefined number of nodes and corresponding blockchain dumps. If it is so, I only need to know, how many nodes must be in these configurations.
> @realloc @alexvanin ?

I think we want to target **one** and **seven** alphabet node configurations. First for debug and latter to model real network setup. However I wonder how we gonna do it. It requires different side chain dumps and we wanted to have some sort of side chain dump generator right in neofs-dev-env, if I understood correctly. 

Can you elaborate your thoughts on how this should be done?

**Comment by cthulhu-rider** [comment]
CN∈IR now https://github.com/nspcc-dev/neofs-node/blob/35def8436a7316db4511845b6ac2020c2ed6f313/config/example/ir.yaml#L23
